# Generated by Django 5.0.1 on 2024-02-12 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0005_create_groupe_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="recipients",
            field=models.ManyToManyField(related_name="received_letter", to="mentorship.teacher"),
        ),
        migrations.AlterField(
            model_name="email",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_letters",
                to="mentorship.student",
            ),
        ),
    ]
