# Generated by Django 5.0.1 on 2024-02-13 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0005_create_groupe_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="recipients",
        ),
        migrations.AddField(
            model_name="email",
            name="recipients",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_letter",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
