# Generated by Django 5.0.1 on 2024-02-12 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0006_alter_email_recipients_alter_email_sender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="recipients",
        ),
        migrations.AddField(
            model_name="email",
            name="recipients",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_letter",
                to="mentorship.teacher",
            ),
        ),
    ]
