# Generated by Django 5.0.1 on 2024-02-13 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0007_remove_email_recipients_email_recipients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="recipients",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_letter",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_letters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
