# Generated by Django 5.0.1 on 2024-02-13 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0006_remove_email_recipients_email_recipients"),
        ("mentorship", "0007_remove_email_recipients_alter_email_sender_and_more"),
        ("mentorship", "0008_alter_email_recipients_alter_email_sender"),
    ]

    operations = []
